export const boardsDispatchConstants = {
  CREATE_NEW_BOARD:"CREATE_NEW_BOARD",
  UPDATE_BOARD : "UPDATE_BOARD",
  DELETE_BOARD: "DELETE_BOARD",
  CREATE_NEW_TASK: "CREATE_NEW_TASK",
  UPDATE_TASK : "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  CREATE_NEW_COLUMN: "CREATE_NEW_COLUMN",
  DELETE_COLUMN:"DELETE_COLUMN"
}

export const pomodoroDispatchConstants = {
  CREATE_NEW_POMO_TASK:"CREATE_NEW_POMO_TASK",
  UPDATE_POMO_TASK:"UPDATE_POMO_TASK",
  DELETE_POMO_TASK:"DELETE_POMO_TASK",
  GET_ALL_POMO_TASKS:"GET_ALL_POMO_TASKS"
}

export const authDispatchConstants = {
  LOGIN:"LOGIN",
  LOGOUT:"LOGOUT"
}

export const USER_TOKEN = "userToken";
